backend:
  name: gitea
  repo: stefenmarg/eleventy-static-cms-template
  app_id: 06b24854-8c27-45bf-b5a3-d0cde9ae3d92
  branch: main
  api_root: https://codeberg.org/api/v1
  base_url: https://codeberg.org
  auth_endpoint: https://codeberg.org/login/oauth/authorize
  site_domain: https://eleventy-static-cms-template.vercel.app/

media_folder: "src/media/assets"
public_folder: "src/media"

site_url: https://eleventy-static-cms-template.vercel.app/

collections:
  - name: "Settings"
    label: "Settings"
    files:
      - label: "Site settings"
        name: "site_items"
        file: "src/_data/settings.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string", default: "Setting name" }
              - { label: "Value", name: "value", widget: "text", default: "Setting value" }

      - label: "Site contact"
        name: "contact_items"
        file: "src/_data/contact.json"
        fields:
          - label: "Contact Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Contact Option", name: "name", widget: "string", default: "Contact name" }
              - { label: "FA Icon Class", name: "fa_icon", widget: "string", default: "fa-solid fa-question" }
              - { label: "Contact Value", name: "value", widget: "text", default: "Contact value" }

      - label: "Site Navigation"
        name: "navigation_items"
        file: "src/_data/header.json"
        fields:
          - label: "Nav Links"
            name: "items"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string", default: "Navigation Label" }
              - { label: "URL", name: "href", widget: "string", default: "https://example.com" }

  - name: "team"
    label: "Team"
    files:
      - label: "Team Members"
        name: "team"
        file: "src/_data/team.json"
        fields:
          - label: "Team Members"
            name: "items"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string", default: "Username" }
              - { label: "Avatar URL", name: "icon", widget: "string", default: "https://placehold.co/256x256" }
              - { label: "Description", name: "desc", widget: "text", default: "Your description here" }
  
  - name: "Projects"
    label: "Projects"
    folder: "src/posts/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{name}}"
    fields:
      - { label: "Title", name: "title", widget: "string", default: "New project" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Internal Tags", name: "tags", widget: "list", default: "project" }
      - { label: "Category", name: "tag", widget: "select", options: ["Design", "Dev", "Research", "Marketing", "Other"], default: "Dev" }
      - { label: "Status", name: "status", widget: "select", options: ["In progress", "Completed"], default: "In progress" }
      - { label: "Description", name: "desc", widget: "text", default: "Your description here." }
      - { label: "Body", name: "body", widget: "markdown" }
    
  - name: "Publications"
    label: "Publications"
    folder: "src/posts/publications"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string", default: "New publication" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Type", name: "tag", widget: "select", options: ["Journal", "Conference", "Preprint", "Report"], default: "Journal" }
      - { label: "Description", name: "desc", widget: "text", default: "Your description here." }
      - { label: "URL", name: "href", widget: "string", default: "https://" }
      - { label: "Body", name: "body", widget: "markdown", required: false }